// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20220820004058_Seed3")]
    partial class Seed3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Bio = "Albert likes long walks on the beach. He also likes long walks absolutely everywhere else too.",
                            Gender = "Male",
                            Name = "Albert",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 8,
                            Bio = "Bob is very friendly but has a strange coat for a dog and is unusually large. Big fan of bamboo though.",
                            Gender = "Unknown",
                            Name = "Bob",
                            Species = "Panda"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 8,
                            Bio = "Charlie's hobbies include sleeping, eating, asking for head-pats and promptly walking away when you offer them.",
                            Gender = "Female",
                            Name = "Charlie",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 64,
                            Bio = "Wanted by several international policing agencies for arson. Do not allow near matches unsupervised. Likes Cheese Puffs.",
                            Gender = "Female",
                            Name = "Diana",
                            Species = "Capybara"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 506,
                            Bio = "Despite Greggory's unique appearance he makes fast friends and loves playing fetch. Very difficult to sneak up on though so hide-and-seek is probably out of the question.",
                            Gender = "Unknown",
                            Name = "Greggory",
                            Species = "Beholder"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 32,
                            Bio = "Pure speed. Ka-chow.",
                            Gender = "Male",
                            Name = "Turbo",
                            Species = "Narwhal"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 28,
                            Bio = "Tried out for the Globo Gym Purple Cobras and made the team",
                            Gender = "Male",
                            Name = "Lazer",
                            Species = "Narwhal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
