// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    partial class AnimalShelterApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelterApi.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Age = 7,
                            Gender = "Male",
                            Name = "Al",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 2,
                            Age = 10,
                            Gender = "Unknown",
                            Name = "Bobbi",
                            Species = "Panda"
                        },
                        new
                        {
                            PetId = 3,
                            Age = 2,
                            Gender = "Male",
                            Name = "Charlie",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 4,
                            Age = 4,
                            Gender = "Female",
                            Name = "La Rata Alta",
                            Species = "Chihuahua"
                        },
                        new
                        {
                            PetId = 5,
                            Age = 22,
                            Gender = "Male",
                            Name = "Buddy",
                            Species = "Narwhal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
